gcp_service_account_path = "C:/Users/Digaum/OneDrive/Documentos/gameficacao-myhome-70d47222b273.json"
gs_sync_enabled = true
gs_users_sheet_id = ""
gs_users_ws = "users"
gs_transactions_sheet_id = ""
gs_transactions_ws = "transactions"
